### ISSUE TITLE
A few things

### ISSUE THREAD

**Issue by autumn-smellegy** [vonpawn/npc-idle-timer-plugin#4]
I've been using this plugin recently and noticed a few issues:

1. The default timer has a max value of 300, and when it's at 300 you can't press the little up arrow anymore. The custom timer also has a max value of 300, but it will let you press the up arrow after that. When you do this and enable the custom timer, the timer just doesn't show up on NPCs.
2. The timer offers the option of counting in seconds or ticks, but in both cases the max value is still 300. 300 seconds makes sense as it's 5 minutes, which is the normal monster idle despawn timer, but 300 ticks does not, because 300 ticks is 3 minutes. It should allow 500 ticks if you want it to be consistent, or just allow a higher value in general.
3. The limit of 300s / 5 minutes is actually not ideal for my use case. I'm using it to track fishing spots, which can last for a maximum of 530 ticks, or 318s. It would be nice if the max value was higher.

I think all three could be solved by just increasing the max value. Maybe make it 1000 or something. Seems like a small change so I could probably make a PR.

**Comment by lejeffe** [comment]
Increased the max value
